Repository voxpupuli/crafty, pull requests merged in 2024-01, with the labels that each got.

#26 update documentation on new version schema
  README.md
Labels: documentation

#30 Update release instructions
  docs/how-to-release.md
Labels: documentation

#29 add ha example
  README.md
  puppet/ha/.gitignore
  puppet/ha/README.md
  puppet/ha/clean.sh
  puppet/ha/compose.yaml
  puppet/ha/nginx-ssl/.gitignore
  puppet/ha/nginx.conf
  puppet/ha/puppet.conf
Labels: documentation, enhancement

#34 Update container versions
  puppet/oss/compose.yaml
Labels: enhancement
